Fix license/copyright notices
cartesi/machine-emulator-tools pull request #17
Opened 2023-07-27 13:27 UTC by diegonehab

Add new license/copyright notice to all source-code files.

2023-08-04 00:03 UTC, mpolitzer approved these changes

2023-08-07 14:34 UTC, vfusco approved these changes

2023-08-07 15:07 UTC, mpolitzer submitted a review, later dismissed

2023-08-07 15:55 UTC, vfusco requested changes

2023-08-07 15:55 UTC, vfusco commented on linux/utils/flashdrive
> +
Were the permissions changed by purpose?

2023-08-11 10:34 UTC, edubart approved these changes

2023-08-11 18:57 UTC, merged