GIO endpoint
cartesi/machine-emulator-tools pull request #42
Opened 2024-04-08 10:26 UTC by alexmikhalevich

This PR implements a General Input/Output endpoint.

2024-04-08 12:31 UTC, mpolitzer requested changes
Required changes:
- "Add a separate sequence counter for gio requests."

Rest left as comments

2024-04-08 12:31 UTC, mpolitzer commented on rollup-http/rollup-http-server/src/http_service.rs
> +    // Write report to linux rollup device
I recognize I'm being pedantic with this comment, but here it goes:
This comment got inserted here and removed on the next commit that states it is only formatting the code.

Formatting first and then implementing a feature (while keeping the formatting) makes the review process easier, consider that for next time.

2024-04-08 12:31 UTC, mpolitzer commented on rollup-http/rollup-http-server/build.rs
> +    println!("cargo:rerun-if-changed={}/libcmt.a", lib_dir);
nice catch!

2024-04-08 12:31 UTC, mpolitzer commented on sys-utils/libcmt/src/io-mock.c
> +static int mock_tx_gio(cmt_io_driver_mock_t *me, struct cmt_io_yield *rr) {
Do you think this is sufficient?

I was under the impression that we should implement a way to feed the GIO response back in.
I tried doing this in this draft: https://github.com/cartesi/machine-emulator-tools/pull/35.

2024-04-08 12:31 UTC, mpolitzer commented on sys-utils/libcmt/src/io-mock.c
> +    return store_next_output(me, "gio-", &me->exception_seq, rr);
Add a separate sequence counter for gio requests.

2024-04-16 12:51 UTC, mpolitzer commented on sys-utils/libcmt/src/io-mock.c
> +static int mock_tx_gio(cmt_io_driver_mock_t *me, struct cmt_io_yield *rr) {
I think the library still should have something regardless of the Rust http server.
The GIO response doesn't necessarily have to be related to the request.
But to be able to test the response path, even the basic stuff.
A gio call should change values in `cmt_io_yield` and put something on rx buffer.

2024-04-16 13:00 UTC, mpolitzer commented on sys-utils/libcmt/src/io-mock.c
> +    me->rx->end = me->rx->begin + file_length;
```suggestion
```

`me->tx` and `me->rx` represent the hardware memory regions mmaped to userspace and should be treated as constants.
The `file_length` information is already present in `rr->data` field.

2024-04-16 14:10 UTC, mpolitzer commented on sys-utils/libcmt/src/io-mock.c
> +    me->rx->end = me->rx->begin + file_length;
It makes sense.
I added a separate function to handle this `cmt_rollup_get_rx`.

https://github.com/cartesi/machine-emulator-tools/pull/29/files#diff-afdab1f6dcd5f7598ab6cd6d0a51a83922a24ccbd484e6eb4a63721e609d362cR222

2024-04-18 13:13 UTC, mpolitzer commented on sys-utils/libcmt/src/io-mock.c
> +    me->rx->end = me->rx->begin + file_length;
Marked this conversation as resolved by mistake. Please remove this line and use `cmt_rollup_get_rx` where appropriate.

2024-04-19 20:54 UTC, mpolitzer approved these changes

2024-04-19 20:59 UTC, edubart approved these changes

2024-04-19 21:28 UTC, merged