Fix inconsistencies in the http server api
cartesi/machine-emulator-tools pull request #60
Opened 2024-05-10 15:55 UTC by alexmikhalevich

2024-06-24 14:30 UTC, diegonehab commented on rollup-http/rollup-http-client/src/rollup.rs
> +    pub app_contract: String,
Silly question. These `String` here are always hex-encoded, right? Otherwise, wouldn't Rust complain when the data isn't a proper UTF-8 string?

2024-06-24 14:31 UTC, diegonehab commented on rollup-http/rollup-http-server/src/http_service.rs
> +                .append_header((hyper::header::CONTENT_TYPE, "text/plain"))
Some error messages start with lower case and others with upper case. We should be consistent.

2024-06-24 14:33 UTC, diegonehab commented on rollup-http/rollup-http-client/src/rollup.rs
> +    pub app_contract: String,
Should there be a `prev_randao` here?

2024-06-24 14:37 UTC, diegonehab commented on rollup-http/rollup-http-server/src/rollup/mod.rs
>      #[validate(range(min = 0x10))] // avoid overlapping with our HTIF_YIELD_MANUAL_REASON_*
I commented on the OpenAPI that we reserve 1, 2, 4. Here you are requiring > 2, but 4 is also reserved.

2024-06-24 14:38 UTC, diegonehab requested changes
See comments.

2024-06-24 14:44 UTC, mpolitzer commented on rollup-http/rollup-http-server/src/rollup/mod.rs
> +                value.data.as_mut_ptr(),
This handles inputs with length <= 32bytes such that:
`0x01`
`0x0000000000000000000000000000000000000000000000000000000000000001`
behave the same.

2024-06-27 19:38 UTC, mpolitzer approved these changes

2024-07-01 15:33 UTC, diegonehab approved these changes

2024-07-01 18:03 UTC, merged